version: 0.2

env:
    secrets-manager:
        AWS_ACCESS_KEY_ID: aws-code-deploy-cdk:AWS_ACCESS_KEY_ID	
        AWS_SECRET_ACCESS_KEY: aws-code-deploy-cdk:AWS_SECRET_ACCESS_KEY

phases:
  pre_build:
    commands:
      - echo setting up environment
      - aws --version
      - export AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY_ID
      - export AWS_SECRET_ACCESS_KEY=$AWS_SECRET_ACCESS_KEY
      - export AWS_DEFAULT_REGION=us-east-1
      - npm install -g aws-cdk
      - cdk doctor
      - python --version
      - sudo apt-get update
      - sudo apt-get install python3-venv -y
      - python3 -m venv .venv
      - ls -a
      - . .venv/bin/activate
      - pip install -r requirements.txt
      - ./install.sh
      - COMMIT_HASH=$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | cut -c 1-7)
      - IMAGE_TAG=build-$(echo $CODEBUILD_BUILD_ID | awk -F":" '{print $2}')
  build:
    commands:
      - echo deploying cdk codes
      - cdk ls
      - cdk diff --all
      - cdk deploy --all --require-approval never 
artifacts:
    files: '**/*'